spring:
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.example.kafka.application.converters.MessageSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.kafka.application.converters.MessageDeSerializer
        binder:
          brokers: localhost:9092

      bindings:
        producer-out-0:
          destination: first-topic
          producer:
            useNativeEncoding: true # Habilita o uso do serializador personalizado
        consumer-in-0:
          destination: first-topic
          consumer:
            use-native-decoding: true # Habilita o uso do desserializador personalizado